ALTER TABLE `users` ADD `maincolor` VARCHAR(9) NOT NULL DEFAULT '#0099FF';
ALTER TABLE `users` ADD `iconcolor` VARCHAR(9) NOT NULL DEFAULT '#FFFFFF';
ALTER TABLE `users` ADD `hudpos` INT(1) NOT NULL DEFAULT '0';
